"""Export and render the strong-attacker per-placement table for the supplement.

Why this exists. The manuscript states, of the eight-placement comparison
against MixVPR, that ``per-placement values are in the Supplementary
Material''. They were not: no supplementary table carried them, because the run
that produced them lives under src/outputs/, which is not committed. This
script slims that run into src/exports/ and renders the table the sentence
promises, so the pointer resolves and a fresh clone can recompute every cell.

What is reported. Top-1 for each energy-matched placement against the uniform
reference on the real place-labelled MSLS manifest, with the paired difference,
a query bootstrap interval and a Wilcoxon signed-rank test over the per-query
differences. Each query is collapsed to its seed-averaged hit rate before
pairing, which is the manuscript's stated unit of inference.

The equivalence margin. The manuscript calls a difference negligible only when
its interval lies inside +-0.01 Top-1, and distinguishes that from ``no benefit
detected''. The table marks which of the two verdicts each row earns, because
on this attacker one cell sits outside the margin while still not being
significant, and collapsing the two would misreport it.
"""
from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Dict, List

import numpy as np
from scipy.stats import wilcoxon

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _pvalue import fmt_p  # noqa: E402

REPO = Path(__file__).resolve().parents[2]

# (export key, printed label). Uniform is the reference and is printed first.
PLACEMENTS = [
    ("uniform", "uniform (ref.)"),
    ("learned", "learned support"),
    ("oracle_grad", "score-gradient"),
    ("anti_oracle_grad", "anti-score-gradient"),
    ("saliency", "saliency"),
    ("center", "centre bias"),
    ("random_fixed", "fixed random"),
    ("edge", "edge magnitude"),
]
KEEP = ["query_id", "placement", "seed", "correct_rank"]
MARGIN = 0.01
BOOT_DRAWS = 10000
BOOT_SEED = 20260910


def slim(source: Path, target: Path) -> int:
    rows: List[dict] = []
    with source.open(newline="", encoding="utf-8") as handle:
        for r in csv.DictReader(handle):
            rows.append({k: r[k] for k in KEEP})
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=KEEP)
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)


def per_query(rows, placement) -> Dict[str, float]:
    hits = defaultdict(list)
    for r in rows:
        if r["placement"] == placement:
            hits[r["query_id"]].append(float(int(r["correct_rank"]) == 1))
    return {q: float(np.mean(v)) for q, v in hits.items()}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source",
                    default=str(REPO / "src" / "outputs" / "placement_mixvpr"
                                / "per_query.csv"))
    ap.add_argument("--export-dir", dest="export_dir",
                    default=str(REPO / "src" / "exports" / "placement_mixvpr_rows"))
    ap.add_argument("--output",
                    default=str(REPO / "paper" / "generated"
                                / "tab_placement_mixvpr.tex"))
    args = ap.parse_args()

    export = Path(args.export_dir) / "per_query.csv"
    source = Path(args.source)
    if source.is_file():
        n = slim(source, export)
        print(f"[export] {n} rows -> {export}")
    if not export.is_file():
        print(f"[fail] neither {source} nor {export} is readable")
        return 1

    rows = list(csv.DictReader(export.open(newline="", encoding="utf-8")))
    seeds = sorted({r["seed"] for r in rows})
    ref = per_query(rows, "uniform")
    rng = np.random.default_rng(BOOT_SEED)

    lines = [
        "% Generated by src/scripts/make_mixvpr_placement_table.py from",
        "% src/exports/placement_mixvpr_rows. Do not edit by hand.",
        r"\begin{table}[htbp]", r"\centering",
        r"\caption{Energy-matched placements against the strong attacker",
        rf"(MixVPR) on the real place-labelled manifest, {len(ref)} query",
        rf"clusters per placement over {len(seeds)} seeds. $\Delta$ is paired",
        r"against the uniform reference with the query as the unit, so",
        r"\emph{positive means worse privacy}; the interval is a query",
        r"bootstrap and $p$ a Wilcoxon signed-rank test. ``Verdict'' is",
        r"\emph{negligible} when the whole interval lies inside the",
        rf"$\pm{MARGIN:.2f}$ Top-1 margin fixed before testing, and",
        r"\emph{none det.} when it does not but the difference is not",
        r"significant.}",
        r"\label{tab:placement_mixvpr}", r"\footnotesize",
        r"\setlength{\tabcolsep}{1.2pt}",
        r"\begin{tabular}{lccccc}", r"\hline",
        r"Placement & Top-1 & $\Delta$ & 95\% CI & $p$ & Verdict \\",
        r"\hline",
    ]
    stats = []
    for key, label in PLACEMENTS:
        arm = per_query(rows, key)
        if not arm:
            continue
        shared = sorted(set(arm) & set(ref))
        top1 = float(np.mean([arm[q] for q in shared]))
        if key == "uniform":
            lines.append(rf"{label:<20} & {top1:.4f} & --- & --- & --- & --- \\")
            stats.append({"placement": key, "top1": top1})
            continue
        diff = np.array([arm[q] - ref[q] for q in shared])
        draws = np.array([diff[rng.integers(0, len(diff), len(diff))].mean()
                          for _ in range(BOOT_DRAWS)])
        lo, hi = (float(x) for x in np.percentile(draws, [2.5, 97.5]))
        nonzero = diff[diff != 0]
        pval = float(wilcoxon(nonzero).pvalue) if len(nonzero) else 1.0
        verdict = ("negligible" if (lo > -MARGIN and hi < MARGIN)
                   else ("none det." if pval >= 0.05 else "significant"))
        lines.append(
            rf"{label:<20} & {top1:.4f} & ${diff.mean():+.4f}$ & "
            rf"$[{lo:+.3f},{hi:+.3f}]$ & {fmt_p(pval)} & {verdict} \\")
        stats.append({"placement": key, "top1": top1, "delta": float(diff.mean()),
                      "ci": [lo, hi], "p": pval, "verdict": verdict})
    lines += [r"\hline", r"\end{tabular}", r"\end{table}", ""]
    Path(args.output).write_text("\n".join(lines), encoding="utf-8")

    (Path(args.export_dir) / "placement_mixvpr_summary.json").write_text(
        json.dumps({"source": str(source.relative_to(REPO)) if source.is_file() else None,
                    "n_queries": len(ref), "seeds": seeds,
                    "margin": MARGIN, "bootstrap_draws": BOOT_DRAWS,
                    "bootstrap_seed": BOOT_SEED, "rows": stats},
                   indent=2) + "\n", encoding="utf-8")
    worst = max((abs(s["delta"]) for s in stats if "delta" in s), default=0.0)
    print(f"[done] wrote {args.output}; largest |delta| {worst:.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
