"""The purification result for all four attackers, in one table.

Four separate per-attacker tables existed but none of them reached the
submitted package, so the manuscript's claim that a trained inverse takes back
"between half and all" of what the direction buys had no table a referee could
check. Four tables also do not fit the page budget, and they are not what the
argument needs: the argument is about the *advantage over the isotropic
control at matched delivered distortion*, before and after the attacker
purifies, which none of the four printed as a row.

This writes that single comparison across every attacker the purifier was run
against, from the same released per-query rows.
"""
from __future__ import annotations

import argparse
import collections
import csv
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from scipy.stats import wilcoxon

REPO = Path(__file__).resolve().parents[2]
import sys
sys.path.insert(0, str(REPO / "src" / "scripts"))
from _pvalue import fmt_p  # noqa: E402

ATTACKERS = [
    ("per_query.csv", "ResNet18"),
    ("per_query_mixvpr.csv", "MixVPR"),
    ("per_query_patchnetvlad.csv", "Patch-NetVLAD"),
    ("per_query_vit.csv", "ViT-B/16"),
]
ARMS = [("direction", "direction"), ("hardened", "hardened")]


def load(path: Path):
    per: Dict[Tuple[str, str], Dict[str, list]] = collections.defaultdict(
        lambda: collections.defaultdict(list))
    place: Dict[str, str] = {}
    for r in csv.DictReader(open(path, newline="", encoding="utf-8")):
        key = (r["condition"], r["purifier"])
        per[key][r["query_id"]].append(1.0 if int(r["correct_rank"]) == 1 else 0.0)
        place[r["query_id"]] = r["correct_place"]
    return ({k: {q: float(np.mean(v)) for q, v in d.items()}
             for k, d in per.items()}, place)


def boot(d: np.ndarray, groups, n: int, seed: int):
    rng = np.random.default_rng(seed)
    idx = collections.defaultdict(list)
    for i, g in enumerate(groups):
        idx[g].append(i)
    keys = sorted(idx)
    out = np.empty(n)
    for b in range(n):
        pick = rng.integers(0, len(keys), len(keys))
        out[b] = d[np.concatenate([idx[keys[j]] for j in pick])].mean()
    return tuple(float(x) for x in np.percentile(out, [2.5, 97.5]))


def contrast(per, place, a, b, n_boot, seed):
    arm, ref = per[a], per[b]
    qs = sorted(set(arm) & set(ref))
    d = np.array([arm[q] - ref[q] for q in qs])
    lo, hi = boot(d, [place[q] for q in qs], n_boot, seed)
    try:
        pv = float(wilcoxon(d).pvalue)
    except ValueError:
        pv = 1.0
    return float(d.mean()), lo, hi, pv


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--export-dir", dest="export_dir",
                    default=str(REPO / "src/exports/purification"))
    ap.add_argument("--n-boot", dest="n_boot", type=int, default=10000)
    ap.add_argument("--out", default=str(
        REPO / "paper/generated/tab_purification_summary.tex"))
    args = ap.parse_args()

    body = []
    for seed, (fname, label) in enumerate(ATTACKERS):
        path = Path(args.export_dir) / fname
        if not path.exists():
            print(f"[skip] {path} absent")
            continue
        per, place = load(path)
        body.append(rf"\multicolumn{{6}}{{l}}{{\textit{{{label}}}}} \\")
        for arm, pur in ARMS:
            if (arm, "none") not in per:
                continue
            # what the release buys over the control, neither side purified
            d0, lo0, hi0, _ = contrast(per, place, (arm, "none"),
                                       ("isotropic", "none"), args.n_boot, seed)
            # and with the attacker purifying both sides, which is the
            # comparison that decides whether the defense survives
            d1, lo1, hi1, p1 = contrast(per, place, (arm, pur),
                                        ("isotropic", "isotropic"),
                                        args.n_boot, seed + 41)
            kept = (d1 / d0 * 100.0) if d0 < -1e-9 else float("nan")
            kepts = "---" if not np.isfinite(kept) else rf"{max(kept, 0.0):.0f}\%"
            name = "direction" if arm == "direction" else "hardened"
            body.append(
                rf"\quad {name} & ${d0:+.4f}$ & $[{lo0:+.3f},{hi0:+.3f}]$ & "
                rf"${d1:+.4f}$ & $[{lo1:+.3f},{hi1:+.3f}]$ & "
                rf"{kepts}~({fmt_p(p1)}) \\")

    lines = [
        "% Generated by src/scripts/make_purification_summary_table.py from",
        "% src/exports/purification. Do not edit by hand.",
        r"\begin{table}[t]", r"\centering",
        r"\caption{What a trained inverse takes back, on every attacker it was "
        r"run against. A residual denoiser is trained on released/clean pairs "
        r"from a place-disjoint split and applied before the attacker embeds. "
        r"Each row is the release's advantage over the isotropic control at "
        r"identical delivered distortion: first with neither side purified, "
        r"then with the attacker purifying both, which is the comparison that "
        r"decides whether the defense survives. ``Kept'' is the share of the "
        r"unpurified advantage that remains, and is what the manuscript's "
        r"``between half and all'' quantifies. Intervals are place-clustered "
        r"over the held-out split; $p$ is a signed-rank test on the purified "
        r"contrast. Negative is better privacy.}",
        r"\label{tab:purification_summary}",
        r"\footnotesize",
        r"\setlength{\tabcolsep}{2.5pt}",
        r"\begin{tabular}{lccccc}", r"\hline",
        r" & \multicolumn{2}{c}{neither purified} & "
        r"\multicolumn{2}{c}{both purified} & \\",
        r"Arm & $\Delta$ & 95\% CI & $\Delta$ & 95\% CI & Kept ($p$) \\",
        r"\hline", *body, r"\hline", r"\end{tabular}", r"\end{table}",
    ]
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[done] wrote {out}")
    for b in body:
        print("  " + b.replace(r"\\", "").replace("&", " ").strip())
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
