"""Render the privacy-utility frontier table with uncertainty on every drop.

Utility comes from src/exports/tifs_a5 (or src/outputs/tifs_a5): dataset-level
mIoU over 200 VOC images, intersections and unions pooled per class before the
ratio. The drop is mIoU(clean) minus mIoU(condition) on the same images, and
its 95% interval is a paired bootstrap that resamples images and recomputes
both terms on the same resample -- the marginal interval of each mIoU is far
wider and is not the estimand a tolerance is judged against.

Privacy comes from the serialized-release exports (tifs_a8_mse5.0, tifs_a8,
tifs_a8_mse60.0, tifs_a8_hi): Top-1 on the float release over 200 queries,
one seed, with a query bootstrap.

Admissibility against the declared tolerance is reported in three states, not
two: a cell whose interval lies within the tolerance, one whose interval
straddles it, and one whose interval lies beyond it.
"""
from __future__ import annotations

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
BUDGETS = [(5.0, "tifs_a8_mse5.0"), (15.68, "tifs_a8"), (60.0, "tifs_a8_mse60.0"), (241.5, "tifs_a8_hi")]
CONDS = [("isotropic", "isotropic"), ("direction", "direction"), ("direction (EOT)", "direction (EOT)")]
CANON = {"hardened": "direction (EOT)", "hardened_direction": "direction (EOT)", "direction_eot": "direction (EOT)"}


def root_for(name: str) -> Path:
    for base in (REPO / "src" / "outputs", REPO / "src" / "exports"):
        if (base / name).is_dir():
            return base / name
    raise FileNotFoundError(name)


def miou(rows) -> float:
    inter, union = defaultdict(int), defaultdict(int)
    for r in rows:
        for cls, (i, u) in (r.get("seg_iu") or {}).items():
            inter[cls] += int(i)
            union[cls] += int(u)
    vals = [inter[c] / union[c] for c in union if union[c]]
    return float(np.mean(vals))


def utility(budget: float, rng, n=2000):
    base = root_for("tifs_a5")
    d = next(x for x in base.glob("segmentation_mse*")
             if abs(float(x.name.rsplit("mse", 1)[1]) - budget) < 1e-6)
    seen = {}
    for line in (d / "per_image.jsonl").open(encoding="utf-8"):
        if line.strip():
            r = json.loads(line)
            seen[(r["image_id"], r["condition"], r.get("seed"))] = r
    by = defaultdict(dict)
    for r in seen.values():
        by[CANON.get(r["condition"], r["condition"])][r["image_id"]] = r
    clean = by["clean"]
    out = {"clean": (miou(list(clean.values())), None, None)}
    for cond, _ in CONDS:
        cr = by.get(cond)
        if not cr:
            continue
        ids = sorted(set(clean) & set(cr))
        point = miou([clean[i] for i in ids]) - miou([cr[i] for i in ids])
        boots = []
        for _ in range(n):
            pick = [ids[j] for j in rng.integers(0, len(ids), len(ids))]
            boots.append(miou([clean[i] for i in pick]) - miou([cr[i] for i in pick]))
        out[cond] = (miou([cr[i] for i in ids]), point, (float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5))))
    return out


def privacy(tree: str, rng, n=5000):
    rows = [r for r in csv.DictReader((root_for(tree) / "serialized_release.csv").open(newline="", encoding="utf-8"))
            if r["serialisation"] == "float"]
    out = {}
    for raw in sorted(set(r["condition"] for r in rows)):
        v = np.array([float(r["top1"]) for r in rows if r["condition"] == raw])
        boots = [v[rng.integers(0, len(v), len(v))].mean() for _ in range(n)]
        out[CANON.get(raw, raw)] = (float(v.mean()), float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5)))
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tolerance", type=float, default=0.05)
    ap.add_argument("--output", default=str(REPO / "paper" / "generated" / "tab_frontier.tex"))
    ap.add_argument("--seed", type=int, default=20260909)
    args = ap.parse_args()
    rng = np.random.default_rng(args.seed)
    tol = args.tolerance

    blocks, clean_vals = [], []
    for budget, tree in BUDGETS:
        u, p = utility(budget, rng), privacy(tree, rng)
        clean_vals.append(u["clean"][0])
        rows = []
        for cond, label in CONDS:
            if cond not in u or cond not in p:
                continue
            m, drop, (lo, hi) = u[cond]
            t1, t1lo, t1hi = p[cond]
            state = r"$\checkmark$" if hi <= tol else (r"$\sim$" if lo < tol else "---")
            rows.append(rf"  & {label:<15} & {t1:.3f} [{t1lo:.3f},{t1hi:.3f}] & {m:.4f} & {drop:.4f} [{lo:.3f},{hi:.3f}] & {state} \\")
        blocks.append((budget, rows))
    clean = float(np.mean(clean_vals))

    lines = [
        "% Generated by src/scripts/make_frontier_table.py from tifs_a5 (utility) and",
        "% tifs_a8_mse5.0 / tifs_a8 / tifs_a8_mse60.0 / tifs_a8_hi (privacy).",
        "% Do not edit by hand.",
        r"\begin{table}[t]",
        r"\centering",
        r"\caption{Privacy against measured downstream utility over four delivered-MSE",
        rf"budgets, one seed per cell; clean mIoU ${clean:.4f}$ throughout. Drop is",
        r"mIoU lost on the same 200 images, with a paired image-bootstrap 95\%",
        r"interval; Top-1 carries a query-bootstrap interval. Against the",
        rf"${tol:.2f}$ tolerance declared in advance a drop interval lies within it",
        r"($\checkmark$), straddles it ($\sim$), or lies beyond it (---). Clean Top-1",
        r"is $0.197$; no $\checkmark$ or $\sim$ cell moves it. Retrieval is on MSLS",
        r"and utility on VOC, paired by budget, not by image.}",
        r"\label{tab:frontier}",
        r"\resizebox{\columnwidth}{!}{%",
        r"\begin{tabular}{llcccc}",
        r"\hline",
        r"MSE & Condition & Top-1 $\downarrow$ [95\% CI] & mIoU $\uparrow$ & Drop [95\% CI] & Adm. \\",
        r"\hline",
    ]
    for budget, rows in blocks:
        lines.append(rf"\multirow{{{len(rows)}}}{{*}}{{${budget:g}$}}")
        lines += rows
        lines.append(r"\hline")
    lines += [r"\end{tabular}}", r"\end{table}", ""]
    Path(args.output).write_text("\n".join(lines), encoding="utf-8")
    print(f"[done] wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
