"""Render the per-condition adaptive-attacker table from the evaluation export.

Reads src/exports/tifs_a6_eval (or src/outputs/tifs_a6_eval when present):
one CSV per (training exposure, gallery mode), each holding the 200 held-out
queries under two evaluated releases -- the isotropic control and the
three-surrogate direction (`transfer_3`). `baseline_hardened.csv` is the
unadapted, pretrained attacker on the same queries and is the reference every
row is paired against.

Intervals are place-clustered: the 200 held-out queries carry 134 distinct
`correct_place` labels, and resampling places rather than queries is what the
manuscript does for every direction contrast. Point estimates are exact means
and do not depend on the resampling seed.
"""
from __future__ import annotations

import argparse
import csv
from collections import defaultdict
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parents[2]
EXPOSURES = [("isotropic", "isotropic noise"),
             ("direction", "direction"),
             ("hardened_direction", "hardened direction")]
GALLERIES = [("stock", "fixed index"), ("rebuilt", "re-indexed")]
EVALS = [("isotropic", "isotropic"), ("transfer_3", "direction")]


def per_query(path: Path, cond: str):
    hits, place = defaultdict(list), {}
    with path.open(newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            if r["condition"] != cond:
                continue
            hits[r["query_id"]].append(1.0 if int(r["correct_rank"]) == 1 else 0.0)
            place[r["query_id"]] = r["correct_place"]
    return {q: float(np.mean(v)) for q, v in hits.items()}, place


def place_bootstrap(a, b, place, rng, n=10000):
    qs = sorted(set(a) & set(b))
    diff = {q: a[q] - b[q] for q in qs}
    groups = defaultdict(list)
    for q in qs:
        groups[place[q]].append(diff[q])
    clusters = list(groups.values())
    point = float(np.mean([diff[q] for q in qs]))
    boots = []
    for _ in range(n):
        pick = rng.integers(0, len(clusters), len(clusters))
        boots.append(np.mean([v for i in pick for v in clusters[i]]))
    return point, float(np.percentile(boots, 2.5)), float(np.percentile(boots, 97.5)), len(clusters)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default=None)
    ap.add_argument("--output", default=str(REPO / "paper" / "generated" / "tab_adaptive.tex"))
    ap.add_argument("--seed", type=int, default=20260908)
    args = ap.parse_args()
    root = Path(args.root) if args.root else next(
        p for p in (REPO / "src" / "outputs" / "tifs_a6_eval", REPO / "src" / "exports" / "tifs_a6_eval") if p.is_dir())
    rng = np.random.default_rng(args.seed)

    base = {c: per_query(root / "baseline_hardened.csv", c) for c, _ in EVALS}
    lines = [
        "% Generated by src/scripts/make_adaptive_attacker_table.py from",
        f"% {root.relative_to(REPO)}. Do not edit by hand.",
        r"\begin{table}[htbp]",
        r"\centering",
        r"\caption{Adaptive attacker, per condition. Each row fine-tunes the last",
        r"block of the ResNet18 attacker on one training exposure and evaluates it,",
        r"either with the gallery still indexed by the original model (fixed index)",
        r"or with the gallery re-embedded by the adapted encoder (re-indexed), on",
        r"the 200 held-out queries under two releases. $\Delta$ is Top-1 minus the",
        r"unadapted attacker on the same queries, with a 95\% bootstrap interval",
        r"clustered on the 134 places those queries occupy; \emph{positive means",
        r"adaptation helped the attacker}.}",
        r"\label{tab:supp_adaptive}",
        r"\resizebox{\columnwidth}{!}{%",
        r"\begin{tabular}{llcccc}",
        r"\hline",
        r"Trained on & Gallery & Release evaluated & Top-1 & $\Delta$ & 95\% CI \\",
        r"\hline",
    ]
    for c, label in EVALS:
        top1 = float(np.mean(list(base[c][0].values())))
        lines.append(rf"\multicolumn{{3}}{{l}}{{\textit{{unadapted attacker, {label} release}}}} & {top1:.4f} & --- & --- \\")
    lines.append(r"\hline")
    for exp, exp_label in EXPOSURES:
        for gal, gal_label in GALLERIES:
            path = root / f"{exp}_{gal}.csv"
            for i, (c, c_label) in enumerate(EVALS):
                t, place = per_query(path, c)
                point, lo, hi, _ = place_bootstrap(t, base[c][0], place, rng)
                top1 = float(np.mean(list(t.values())))
                first = f"{exp_label} & {gal_label}" if i == 0 else " & "
                star = r"$^{\ast}$" if (lo > 0 or hi < 0) else ""
                lines.append(rf"{first} & {c_label} & {top1:.4f} & ${point:+.4f}${star} & $[{lo:+.3f},{hi:+.3f}]$ \\")
        lines.append(r"\hline")
    lines += [r"\end{tabular}}", r"\end{table}", ""]
    Path(args.output).write_text("\n".join(lines), encoding="utf-8")
    print(f"[done] wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
